spring:
  application:
    name: config-server
  rabbitmq:
    host: 192.168.64.140
    port: 5672
    username: admin
    password: admin

  cloud:
    config:
      server:
        git:
          uri: https://github.com/wanjianwanjian/spring-cloud-repo-springcloud11
          searchPaths: configurationcenter

          #username: your-username
          #password: your-password

server:
  port: 6001

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh