spring:
  application:
    name: order-service

#  rabbitmq:
#    host: 192.168.72.133
#    port: 5672
#    username: admin
#    password: admin

  #server:
  #  port: 8001

eureka:
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

---
spring:
  profiles: order1

server:
  port: 8201
---
spring:
  profiles: order2

server:
  port: 8202