spring:
  application:
    name: user-service



  #server:
  #  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

---
spring:
  profiles: user1

server:
  port: 8101
---
spring:
  profiles: user2

server:
  port: 8102